config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  #get 'admin/index'


  devise_for :admins , :controllers => { registrations: 'registrations' }
  resources :cows
  resources :vet_officers
  resources :farmers
  #get 'static_pages#services'
  get '/services', to: 'static_pages#services'

  devise_scope :admin do
     get '/dashboard', to: 'cows#index'
  end

  post "cows/call_action" => "cows#call_action"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cow.rb
class Cow < ApplicationRecord
	belongs_to :farmer
	belongs_to :vet_officer

	#validates :cow_owner , presence: true
	validates :date_of_birth , presence: true
	validates :weight , presence: true
	validates :color , presence: true
	validates :tag_number , presence: true
	validates :temperature , presence: true
	#validates :vetofficer , presence: true


end

app/models/farmer.rb
class Farmer < ApplicationRecord
	mount_uploader :profile_pic, ProfilePicUploader

	has_many :cows

	validates :name , presence: true
	validates :farm_size , presence: true
	validates :number_of_animals , presence: true
	validates :farm_location , presence: true
	validates :phone_number , presence: true
	#validates :profile_pic , presence: true
	validates :address , presence: true


end

app/models/vet_officer.rb
class VetOfficer < ApplicationRecord
	has_many :cows

		mount_uploader :vprofile_pic, VprofilePicUploader

	validates  :name ,  presence: true
	validates  :location , presence: true
	validates  :phone_number , presence: true
#	validates  :vprofile_pic , presence: true
	validates  :address , presence: true



end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  after_action :store_action



#Redirect after sign in
  def store_action
    return unless request.get?
    if (request.path != "/admins/sign_in" &&
        request.path != "/admins/sign_up" &&
        request.path != "/admins/password/new" &&
        request.path != "/admins/password/edit" &&
        request.path != "/admins/sign_out" &&
        !request.xhr?) # don't store ajax calls
      store_location_for(:admin, "/dashboard")
    end
  end
end

app/controllers/cows_controller.rb
class CowsController < ApplicationController
	#before_action :set_farmer
	#before_action  :set_vet

	def index
    @cows = Cow.all
	end

	def show

	end

    def new
		 @farmer_options = Farmer.all.map{|f| [ f.name, f.id]}
		 @vet_officer_options = VetOfficer.all.map{|v| [ v.name, v.id]}
		# @farmers = Farmer.all
		# @vet_officers = VetOfficer.all
		@cow = Cow.new

	end



	def create
		@cow = Cow.new(cow_params)
		@farmer_options = Farmer.all.map{|f| [ f.name, f.id]}
		@vet_officer_options = VetOfficer.all.map{|v| [ v.name, v.id]}
        # @cow = @farmer.cows.build(cow_params)
        # @cow.VetOfficer_id = vet_officer.id
		if @cow.save
			@success = "Cow added successfully"
			redirect_to cows_path
		else
			@error = "Unable to save. Please try again"
			render 'new'
		end


	end

	def destroy

	end

	def update

	end

	def edit

	end

	private

	def cow_params
		params.require(:cow).permit(:farmer_id,:VetOfficer_id,:cow_owner, :date_of_birth, :weight, :color, :tag_number, :temperature, :status,:vetofficer)
	end

	# def set_farmer
	# 	@farmer = Farmer.find(params[:farmer_id])
	# end

	# def set_vet
  #       @vet_officer = VetOfficer.find(params[:VetOfficer_id])
	# end

end

app/controllers/farmers_controller.rb
class FarmersController < ApplicationController
	def index
		@farmers = Farmer.all
	end

	def show
		@farmer = Farmer.find(params[:id])
	end

	def new
		@farmer = Farmer.new
	end

	def create
		@farmer = Farmer.new(farmer_params)

		if @farmer.save
				@success = "Farmer added successfully"
				redirect_to cows_path
		else
			@error = "Unable to save. Please try again"
			render 'new'
		end

	end

	def update

	end

	def destroy

	end

	def method_name

	end

    private

    def farmer_params
    	params.require(:farmer).permit(:name,:farm_size,:number_of_animals,:farm_location,:phone_number,:address,:profile_pic)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

   private
    def sign_up_params
      params.require(:admin).permit(:email,:password,:password_confirmation)
    end

    def account_update_params
      params.require(:admin).permit(:email,:password,:password_confirmation,:current_password)
    end

#  def after_sign_up_path_for(resource)
#     after_sign_in_path_for(resource)
#   end
    def  after_sign_up_path_for(organisations)
        "/dashboard"
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def dashboard
  end
end

app/controllers/vet_officers_controller.rb
class VetOfficersController < ApplicationController

	def index
		@vet_officers = VetOfficer.all
	end

	def show
		@vet_officer = VetOfficer.find(params[:id])
	end

	def new
		@vet_officer = VetOfficer.new
	end

	def create
		@vet_officer = VetOfficer.new(farmer_params)

		if @vet_officer.save
				@success = "New VetOfficer added"
				redirect_to cows_path
		else
			@error = "Unable to save. Please try again"
				render 'new'
		end

	end

	def update

	end

	def destroy

	end

	def method_name

	end

    private

    def farmer_params
    	params.require(:vet_officer).permit(:name,:location,:phone_number,:address,:vprofile_pic)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cows_helper.rb
module CowsHelper
	def generate_status
		status_array = ["Good","Bad","Unknown"]
		status_array.map do | status|
			[status, status]
		end
		
	end
end

app/helpers/farmers_helper.rb
module FarmersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/vet_officers_helper.rb
module VetOfficersHelper
end

app/views/cows/index.html.erb



  <div class="app app-default">

 <%= render 'layouts/aside' %>

<script type="text/ng-template" id="sidebar-dropdown.tpl.html">
  <div class="dropdown-background">
    <div class="bg"></div>
  </div>
  <div class="dropdown-container">
    <!-- {{list}} -->
  </div>
</script>


<div class="app-container">

  <nav class="navbar navbar-default" id="navbar">
  <div class="container-fluid">
    <div class="navbar-collapse collapse in">
      <ul class="nav navbar-nav navbar-mobile">
        <li>
          <button type="button" class="sidebar-toggle">
            <i class="fa fa-bars"></i>
          </button>
        </li>
        <li class="logo">
          <a class="navbar-brand" href="#"><span class="highlight">-----</span> ---</a>
        </li>
        <li>
          <button type="button" class="navbar-toggle">
            <%= image_tag("profile-img", :class => "profile-img" ) %>
         <!--   <img class="profile-img" src="../assets/images/profile.png"> -->
          </button>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-left">
      <li>  <%= image_tag("true-logo.png",  :width => "80px" , :height => "80px" ) %>   <!--<img src="../assets/images/true-logo.png" width="80px" height="80px">-->  </li>
        <span class="highlight">Your Dashboard</span>
      </ul>

      <ul class="nav navbar-nav navbar-right">
       <li class="navbar-search hidden-sm">
          <input id="search" type="text" placeholder="Search..">
          <button class="btn-search"><i class="fa fa-search"></i></button>
        </li>
        <li class="dropdown notification">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <div class="icon"><i class="fa fa-shopping-basket" aria-hidden="true"></i></div>
            <div class="title">Support Tickets</div>
            <div class="count">1</div>
          </a>
          <div class="dropdown-menu">
            <ul>
              <li class="dropdown-header">Feed</li>
              <li class="dropdown-empty">No New Feed</li>
              <li class="dropdown-footer">
                <a href="#">View All <i class="fa fa-angle-right" aria-hidden="true"></i></a>
              </li>
            </ul>
          </div>
        </li>

        <li class="dropdown notification warning">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <div class="icon"><i class="fa fa-comments" aria-hidden="true"></i></div>
            <div class="title">Unread Messages</div>
            <div class="count">3</div>
          </a>
          <div class="dropdown-menu">
            <ul>
              <li class="dropdown-header">Message</li>
              <li>
                <a href="#">
                  <span class="badge badge-warning pull-right">10</span>
                  <div class="message">
                    <img class="profile" src="https://placehold.it/100x100">
                    <div class="content">
                      <div class="title">"Two Animals have been reported missing.Plea..."</div>
                      <div class="description">Winnie Akoko</div>
                    </div>
                  </div>
                </a>
              </li>
              <li>
                <a href="#">
                  <span class="badge badge-warning pull-right">5</span>
                  <div class="message">
                    <img class="profile" src="https://placehold.it/100x100">
                    <div class="content">
                      <div class="title">"11 of your Animals recently had abnormal temperatures. View more..."</div>
                      <div class="description">Marfo Tony</div>
                    </div>
                  </div>
                </a>
              </li>
              <li>
                <a href="#">
                  <span class="badge badge-warning pull-right">2</span>
                  <div class="message">
                    <img class="profile" src="https://placehold.it/100x100">
                    <div class="content">
                      <div class="title">"Animal JH4322 has not been vaccinated yet.."</div>
                      <div class="description">Link me to Veterinary</div>
                    </div>
                  </div>
                </a>
              </li>
              <li class="dropdown-footer">
                <a href="#">View All <i class="fa fa-angle-right" aria-hidden="true"></i></a>
              </li>
            </ul>
          </div>
        </li>
        <li class="dropdown notification danger">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <div class="icon"><i class="fa fa-bell" aria-hidden="true"></i></div>
            <div class="title">System Notifications</div>
            <div class="count">10</div>
          </a>
          <div class="dropdown-menu">
            <ul>
              <li class="dropdown-header">Notification</li>
              <li>
                <a href="#">
                  <span class="badge badge-danger pull-right">8</span>
                  <div class="message">
                    <div class="content">
                      <div class="title">New Notification</div>
                      <div class="description">Animal JH3443 has temperature above normal</div>
                    </div>
                  </div>
                </a>
              </li>
              <li>
                <a href="#">
                  <span class="badge badge-danger pull-right">5</span>
                  Inbox
                </a>
              </li>
              <li>
                <a href="#">
                  <span class="badge badge-danger pull-right">5</span>
                  Issues Report
                </a>
              </li>
              <li class="dropdown-footer">
                <a href="#">View All <i class="fa fa-angle-right" aria-hidden="true"></i></a>
              </li>
            </ul>
          </div>
        </li>
        <li class="dropdown profile">
          <a href="/html/pages/profile.html" class="dropdown-toggle"  data-toggle="dropdown">
            <!--<img class="profile-img" src="../assets/images/profile.png">-->
                <%= image_tag("true-logo.png",  :class => "profile-img" ) %>
            <div class="title">Profile</div>
          </a>
          <div class="dropdown-menu">
            <div class="profile-info">
              <h4 class="username">Jamal Haji</h4>
            </div>
            <ul class="action">
              <li>
                <a href="#">
                  Profile
                </a>
              </li>
              <li>
                <a href="#">
                  <span class="badge badge-danger pull-right">5</span>
                  My Inbox
                </a>
              </li>
              <li>
                <a href="#">
                  Setting
                </a>
              </li>
              <li>
                <a href="#">
                  Logout
                </a>
              </li>
            </ul>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>







<!--
  <div class="btn-floating" id="help-actions">
  <div class="btn-bg"></div>
  <button type="button" class="btn btn-default btn-toggle" data-toggle="toggle" data-target="#help-actions">
    <i class="icon fa fa-plus"></i>
    <span class="help-text">Shortcut</span>
  </button>
  <div class="toggle-content">
    <ul class="actions">
      <li> </li>
      <li><a href="/pages/vet-profile.php">Connect to Vet Service</a></li>
      <li><a href="/pages/lost.php">Report Lost Animals</a></li>
      <li><a href="/uikits/card.php">Send Notifications</a></li>
    </ul>
  </div>
</div> -->


<div class="row">
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
      <a class="card card-banner card-green-light">
  <div class="card-body">
<img src='http://dreamstartltd.com/wp-content/uploads/cow.png'/>
   <div class="content">
      <div class="title">My Herd</div>
      <div class="value"><span class="sign"></span><%= @cows.try(:count)%></div>
    </div>
  </div>
</a>

  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
      <a class="card card-banner card-blue">
  <div class="card-body">
<img src='http://dreamstartltd.com/wp-content/uploads/cowlost.png'/>
    <div class="content">
      <div class="title">Animals Missing</div>
      <div class="value"><span class="sign"></span>2</div>
    </div>
  </div>
</a>

  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
      <a class="card card-banner card-yellow-light">
  <div class="card-body">
<img src='http://dreamstartltd.com/wp-content/uploads/cowtemp.png'/>
    <div class="content">
      <div class="title">High Temperature </div>
      <div class="value"><span class="sign"></span>11</div>
    </div>
  </div>
</a>

  </div>
</div>

<div class="row">
  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
    <div class="card card-mini">
      <div class="card-header">
        <div class="card-title">Recent Reports</div>
        <ul class="card-action">
          <li>
            <a href="/">
              <i class="fa fa-refresh"></i>
            </a>
          </li>
        </ul>
      </div>
      <div class="card-body no-padding table-responsive">
        <table class="table card-table">
          <thead>
            <tr>
              <th>Animal</th>
              <th class="right">Animal ID</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
          <% for cowe in @cows do %>
            <tr>
              <td>QR<%= cowe.try(:tag_number)%></td>
              <td class="right"><%= cowe.try(:tag_number)%></td>
              <td><span class="badge badge-success badge-icon"><i class="fa fa-check" aria-hidden="true"></i><span><%= cowe.try(:status) %></span></span></td>
            </tr>
            <% end %>
            <!--
            <tr>
              <td>Dolly</td>
              <td class="right">JH4345</td>
              <td><span class="badge badge-success badge-icon"><i class="fa fa-clock-o" aria-hidden="true"></i><span>Healthy</span></span></td>
            </tr>
            <tr>
              <td>Sofolik</td>
              <td class="right">JH4431</td>
              <td><span class="badge badge-danger badge-icon"><i class="fa fa-thermometer-half" aria-hidden="true"></i><span>Temperature above normal</span></span></td>
            </tr>
            <tr>
              <td>Duncan</td>
              <td class="right">JH4210</td>
              <td><span class="badge badge-warning badge-icon"><i class="fa fa-times" aria-hidden="true"></i><span>Vacinnation in 3 days</span></span></td>
            </tr>
            <tr>
              <td>Molly</td>
              <td class="right">JH8836</td>
              <td><span class="badge badge-primary badge-icon"><i class="fa fa-arrow-down" aria-hidden="true"></i><span>Minimal Activity</span></span></td>
            </tr>
            <tr>
              <td>Yaawood</td>
              <td class="right">JH7640</td>
              <td><span class="badge badge-danger badge-icon"><i class="fa fa-credit-card" aria-hidden="true"></i><span>Missing</span></span></td>
            </tr> -->
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
    <div class="card card-tab card-mini">
      <div class="card-header">
        <ul class="nav nav-tabs tab-stats">
          <li role="tab1" class="active">
            <a href="#tab1" aria-controls="tab1" role="tab" data-toggle="tab">All Reports</a>
          </li>
          <li role="tab2">
            <a href="#tab2" aria-controls="tab2" role="tab" data-toggle="tab">By Date</a>
          </li>
        </ul>
      </div>
      <div class="card-body tab-content">
        <div role="tabpanel" class="tab-pane active" id="tab1">
          <div class="row">
            <div class="col-sm-8">
              <div class="chart ct-chart-browser ct-perfect-fourth"></div>
            </div>
            <div class="col-sm-4">
              <ul class="chart-label">
                <li class="ct-label ct-series-a">Total Healthy Animals</li>
                <li class="ct-label ct-series-b">Total Activity</li>
                <li class="ct-label ct-series-c">Vaccinated Recently</li>
                <li class="ct-label ct-series-d">Total Lameness</li>
                <li class="ct-label ct-series-e">Other</li>
              </ul>
            </div>
          </div>
        </div>
        <div role="tabpanel" class="tab-pane" id="tab2">
          <div class="row">
            <div class="col-sm-8">
              <div class="chart ct-chart-os ct-perfect-fourth"></div>
            </div>
            <div class="col-sm-4">
              <ul class="chart-label">
                <li class="ct-label ct-series-a">Total Healthy Animals</li>
                <li class="ct-label ct-series-b">Total Activity</li>
                <li class="ct-label ct-series-c">Vaccinated</li>
                <li class="ct-label ct-series-d">Total Lameness</li>
                <li class="ct-label ct-series-e">Other</li>
              </ul>
            </div>
          </div>
          <date>Date Goes here</date>

        </div>
        <div role="tabpanel" class="tab-pane" id="tab3">
        </div>
      </div>
    </div>
  </div>
  
</div>
  <footer class="app-footer">
  <div class="row">
    <div class="col-xs-12">
      <div class="footer-copyright">
        Copyright © 2016 AniTrack International.
      </div>
    </div>
  </div>
</footer>
</div>

  </div>



app/views/cows/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

		<%= form_for @cow do |f| %>
		 <% if @success %>
		 	<div class="success"><%= @success %></div>

		 	<% else %>

		 	<div class="danger"><%= @error %></div>
		 <% end %>


		<div>


		 <label>  Cow Owner </label>

		       <%= f.select(:farmer_id, options_for_select(@farmer_options),{}, class: 'form-control' ) %>

			</div>

		  <div>
			<label> Vet Officer </label>

     <%= f.select(:vet_officers_id, options_for_select(@vet_officer_options),{},class: 'form-control' )%>

			</div>
			<div>
				<label>Date of Birth</label>
				  <%= f.text_field :date_of_birth ,class: 'form-control' %>

			</div>
			<div>
				<label>Initial Weight</label>

				  <%= f.text_field :weight,class: 'form-control'  %>

			</div>
			<div>

				<label>Color of Cow</label>
				  <%= f.text_field :color,class: 'form-control'  %>

			</div>
			<div>
				<label>Tag Number</label>
				  <%= f.text_field :tag_number ,class: 'form-control' %>

			</div>
			<div>

				<label>Initial Temperature</label>
				  <%= f.text_field :temperature ,class: 'form-control' %>

			</div>
			<div>
				<label>Status</label>
				  <%= f.select :status, generate_status, {},class: 'form-control'  %>

			</div><br>
			<div>
				  <%= f.submit "Add Cow", class: "btn btn-warning"  %>

			</div>
		<% end %>
	</div>
</div>

app/views/farmers/index.html.erb
<div style="margin-top:5%; text-align: center;">
  <h1> Farmer List  </h1>
</div>

  <div class="container">
     <div class="row" >

       <div class="col-md-6">
           <table class="table table-striped">
               <thead>
                <th> Name  </th>
                <th> Location  </th>
                <th> Message </th>
                <th> Edit  </th>
                <th> Delete  </th>
               </thead>
                <tbody>

                <% @farmers.each do |farmer| %>
                <% if @farmers.count > 0 %>
                <tr>
                  <td>  <%= farmer.name %> </td>
                  <td>  <%= farmer.farm_location %></td>
                  <td>
                    <button
                     id="message-farmer"
                     class="btn btn-success message-farmer"
                     farmer  = "<%= farmer.to_json%>"

                    >Message</button>
                  </td>
                  <td><button class="btn btn-primary">Edit</button></td>
                  <td><button class="btn btn-danger"> Delete</button></td>
                </tr>
                <% else %>
                  <h1>No Farmers Yet</h1>
                <% end %>
                <% end %>

              </tbody>
            </table>
        </div>

        <div class="col-md-6">
           <div class="col-md-4">
           </div>
           <div id="message-box" class="col-md-8 hide">
             <br /><br /><br />
             <input type="text" class="form-control"></input><br /><br />
             <textarea id="textarea-message" class="form-control"></textarea><br />
             <button class="btn btn-primary"> confirm Message</button>
          </div>
        </div>

      </div>



   </div>

app/views/farmers/new.html.erb
<!--Form for farmers-->

<div class="row">
  <div class="col-md-6 col-md-offset-3">

	<center><%= form_for(@farmer) do |f| %>
	 <% if @success %>
	 	<div class="success"><%= @success %></div>

	 	<% else %>

	 	<div class="danger"><%= @error %></div>
	 <% end %>
		<div>
			<label>Farmer Name</label>
			  <%= f.text_field :name , class: 'form-control' %>
		</div>

		<div>
			<label>Farm Size</label>
			  <%= f.text_field :farm_size , class: 'form-control' %>

		</div>
		<div>
			<label>Number of Animals</label>

			  <%= f.text_field :number_of_animals , class: 'form-control' %>

		</div>
		<div>
			
			<label>Location of Farm</label>
			  <%= f.text_field :farm_location , class: 'form-control'%>

		</div>
		<div>
			<label>Primary Phone Number</label>
			  <%= f.text_field :phone_number , class: 'form-control' %>

		</div>
		<div>
			
			<label>Address if any</label>
			  <%= f.text_field :address , class: 'form-control'%>

		</div>
		<div>
			<label>Profile Picture</label>
			  <%= f.file_field :profile_pic , class: 'form-control'%>

		</div>
		<div>
			  <%= f.submit "Add New Farmer", class: "btn btn-warning form-control"  %>
		</div>
	<% end %></center>
  </div>
</div>

app/views/layouts/_aside.html.erb
<aside class="app-sidebar" id="sidebar">
  <div class="sidebar-header">
    <a class="sidebar-brand" href="index.php"><span class="highlight">Welcome</span> Jamal</a>
    <button type="button" class="sidebar-toggle">
      <i class="fa fa-times"></i>
    </button>
  </div>
  <div class="sidebar-menu">
    <ul class="sidebar-nav">
      <li class="active">
        <a href="./index.php">
          <div class="icon">
            <i class="fa fa-eye" aria-hidden="true"></i>
          </div>
          <div class="title">Dashboard</div>
        </a>
      </li>
      <li class="@@menu.messaging">
      <%= link_to farmers_path do %>
        <!--<a href="./messaging.php"> -->
          <div class="icon">
            <i class="fa fa-user" aria-hidden="true"></i>
          </div>
          <div class="title">Farmer List</div>
       <!-- </a> -->
        <% end %>
      </li>
      <li class="dropdown ">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <div class="icon">
            <i class="fa fa-connectdevelop" aria-hidden="true"></i>
          </div>
          <div class="title">Manage</div>
        </a>

      </li>
      <li class="dropdown">
      <%= link_to services_path do %>
       <!-- <a href="#" class="dropdown-toggle" data-toggle="dropdown"> -->
          <div class="icon">
            <i class="fa fa-exchange" aria-hidden="true"></i>
          </div>
          <div class="title">Services</div>
      <!-- </a> -->
            <% end %>
      </li>
    </ul>
  </div>
  <div class="sidebar-footer">
    <ul class="menu">
      <li>
        <a href="/" class="dropdown-toggle" data-toggle="dropdown">
          <i class="fa fa-cogs" aria-hidden="true"></i>
        </a>
      </li>
      <li><a href="#"><span class="flag-icon flag-icon-th flag-icon-squared"></span></a></li>
    </ul>
  </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Anitrackgh</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'vendor.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'flat-admin.css', media: 'all', 'data-turbolinks-track': 'reload' %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'app.js', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'vendor.js', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
      <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js', 'data-turbolinks-track': 'reload' %>

  </body>
</html>

app/views/static_pages/home.html.erb
<h1>Landing page / Signup</h1>

<li><%= link_to "Sign Up As Admin" , new_admin_registration_path %> </li>
<li><%= link_to "Login As Admin", new_admin_session_path  %> </li>

app/views/static_pages/services.html.erb
<li> <%= link_to "Add New Animal" , new_cow_path %></li>
  <li> <%= link_to "Add New Farmer" , new_farmer_path %></li>
  <li> <%= link_to "Add VetOfficer" , new_vet_officer_path %> </li>

app/views/vet_officers/index.html.erb
<div style="margin-top:5%; text-align: center;">
  <h1> Vetenary list </h1>
</div>

  <div class="container">
     <div class="row" >

       <div class="col-md-6">
           <table class="table table-striped">
               <thead>
                <th> Name  </th>
                <th> Location  </th>
                <th> Message </th>
                <th> Edit  </th>
                <th> Delete  </th>
               </thead>
                <tbody>

                <% @vet_officers.each do |vet_officer| %>
                <% if @vet_officers.count > 0 %>
                <tr>
                  <td>  <%= vet_officer.name %></td>
                  <td>  <%= vet_officer.location %></td>
                  <td>
                    <button
                     id="message-farmer"
                     class="btn btn-success message-vet"
                     vet_officer  = "<%= vet_officer.to_json%>"
                    >Message</button>
                  </td>
                  <td><button class="btn btn-primary">Edit</button></td>
                  <td><button class="btn btn-danger"> Delete</button></td>
                </tr>
                <% else %>
                  <h1>No Vet Officers Yet</h1>
                <% end %>
                <% end %>

              </tbody>
            </table>
        </div>


      </div>



   </div>

app/views/vet_officers/new.html.erb
<div style="margin-top:5%; text-align: center;">
  <h1>New Vet Officer</h1>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

		<center><%= form_for @vet_officer do |f| %>
		 <% if @success %>
		 	<div class="success"><%= @success %></div>

		 	<% else %>

		 	<div class="danger"><%= @error %></div>
		 <% end %>
			<div>
				<label>Vet Officer Name</label>
				  <%= f.text_field :name , class: 'form-control'%>
			</div>

			<div>
				<label>Office Location</label>
				  <%= f.text_field :location , class: 'form-control'%>

			</div>
			<div>
				<label>Phone Number</label>

				  <%= f.text_field :phone_number , class: 'form-control'%>

			</div>
			<div>

				<label>Office Address</label>
				  <%= f.text_field :address, class: 'form-control' %>

			</div>
			<div>
				<label>Profile Picture</label>
				  <%= f.file_field :vprofile_pic , class: 'form-control'%>

			</div>

			<div>
				  <%= f.submit "Add New Vet.Officer", class: "btn btn-warning form-control " %>

			</div>
		<% end %></center>
	</div>
</div>